version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
  app:
    build:
      context: .  # Usar el Dockerfile en el directorio actual
    ports:
      - 13000:3000
